// Generated by https://quicktype.io
import { EstructureMovie } from "./estructureMovie";
export interface StructureMovies {
  page: number;
  results: EstructureMovie[];
  total_pages: number;
  total_results: number;
}

export enum OriginalLanguage {
  En = "en",
  Es = "es",
  Ko = "ko",
  Nl = "nl",
}
